# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e06f3034265b1eb868699685375c5cfbcebe1d9bef9318e7c79331abf0684136da0046b62e2da27896d921ce77d2c8ce78d7b3987e0c8f138747c78680eaf27

test:
  secret_key_base: 0e3a7d3483c8ef0a0c19b97e730eb1a5e8f824a8be98ce4d6d74c395e10a5ecc61de2edeb43c1ff802528e31de14df14848c392e97550bce507049b8c6d0fae6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
